name: Deploy Worker

on:
  push:
    branches:
      - "main"
    paths:
      - "apps/worker/**"
      - "packages/typescript-config/**"
      - ".github/workflows/deploy-worker.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t rtpa25/demo-gcp-worker -f apps/worker/Dockerfile --build-arg PROJECT=worker .

      - run: docker push rtpa25/demo-gcp-worker
