name: Deploy API

on:
  push:
    branches:
      - "main"
    paths:
      - "apps/api/**"
      - "packages/typescript-config/**"
      - ".github/workflows/deploy-api.yaml"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - run: docker build -t rtpa25/demo-gcp-api -f apps/api/Dockerfile .

      - run: docker push rtpa25/demo-gcp-api
